### ISSUE TITLE
There're no tags

### ISSUE THREAD

**Issue by korotovsky** [Levelab/doctrine-discriminator-bundle#1]

**Comment by korotovsky** [comment]
@init-penguin ping.

**Comment by init-penguin** [comment]
pong. which tags do you mean?

**Comment by korotovsky** [comment]
@init-penguin Any stable tag. Like 0.1

**Comment by init-penguin** [comment]
My bad, I'll do it as soon as I fix dependencies in composer.

**Comment by korotovsky** [comment]
Okay. Let me know when you finish it.

**Comment by init-penguin** [comment]
Seems to be done.

**Comment by korotovsky** [comment]
Thanks. :+1:
